# Generated by Django 6.0.1 on 2026-01-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
