# Generated by Django 6.0.1 on 2026-01-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0003_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='meta_semanal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
