# Generated by Django 6.0.1 on 2026-01-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0004_disciplina_meta_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='cor',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
