# Generated by Django 6.0.1 on 2026-01-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0005_disciplina_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='meta_semanal',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
