# Generated by Django 6.0.1 on 2026-01-14 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0006_alter_disciplina_meta_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoestudo',
            name='data_fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='horas',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
