# Generated by Django 6.0.1 on 2026-01-14 17:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0007_sessaoestudo_data_fim_sessaoestudo_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisao',
            name='data_proxima',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisao',
            name='data_ultima',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revisao',
            name='facilidade',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='revisao',
            name='intervalo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='revisao',
            name='repeticoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revisao',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyplanner.disciplina'),
        ),
    ]
